### ISSUE TITLE
Mock up front end and start site map

### ISSUE THREAD

**Issue by Linkinlog** [Linkinlog/HomeBurrow#2]
- [x] Get a general feel for what pages the front end will have and then put them in here
- [x] Design one or more of the pages in Figma or similar and then post link in here

**Comment by mitrerogelio** [comment]
Pages:
- Home
- Ecosystem
  - Get Started
- Support
  - FAQ 
- Login

**Comment by mitrerogelio** [comment]
Preliminary design for testing: 
![image](https://user-images.githubusercontent.com/53048041/189013087-4a4b5909-86ac-4d2a-ac61-6508efc80c32.png)
