### ISSUE TITLE
Components not Rendering

### ISSUE THREAD

**Issue by mitrerogelio** [Linkinlog/HomeBurrow#20]
There seems to be something wrong with the children prop and I can't get my components to render properly (anymore).

Not sure if this is a Next.js, TypeScript, or React issue.

We can certainly work on this together, as I'd love to learn how all these pieces fit together.

Note: I've run into this while working on #12

**Comment by Linkinlog** [comment]
Fixed by reverting _app.tsx

**Comment by mitrerogelio** [comment]
Wonderful work
