### ISSUE TITLE
README is not up to date with about

### ISSUE THREAD

**Issue by Linkinlog** [Linkinlog/HomeBurrow#5]
In the about we changed it to "Next.js / Gin" since we added the Gin framework to Go. However the `README.md` file still says Go. Update the file to be the same as our about section.

**Comment by SRADHA-SURESH12** [comment]
Hello there! Can I work on this issue?

**Comment by Linkinlog** [comment]
Apologies. After some research it was decided to stick with Go and not Gin for now, closing.
